
spring:
  jpa:
    properties:
      hibernate:
        default_schema: customers
  flyway:
    clean-disabled: true
    baseline-on-migrate: true
    user: postgres
    password: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
  datasource:
    username: postgres
    password: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: demo
server:
  port: 8085
