CREATE SCHEMA IF NOT EXISTS managers;

CREATE TABLE managers (
                           id BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                           first_name_ru TEXT NOT NULL,
                           last_name_ru TEXT NOT NULL,
                           middle_name_ru TEXT NOT NULL,
                           first_name_en TEXT NOT NULL,
                           last_name_en TEXT NOT NULL,
                           middle_name_en TEXT NOT NULL,
                           phone_number TEXT,
                           time_zone TEXT
);